import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "./components/dashboard/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sans`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster richColors closeButton />
          <style jsx global>
            {`
              :root {
                --font-geist-sans: ${geistSans.style.fontFamily};
                --font-geist-mono: ${geistMono.style.fontFamily};
                --font-primary: var(--font-geist-sans);
                --font-secondary: var(--font-geist-mono);
                --color-primary: #03ffe0;
                --color-secondary: #4c65e4;
                --color-accent: #7c87f8;
                --color-muted: #e0e0e0;
                --color-muted-foreground: #646464;
                --color-accent-foreground: #ffffff;
                --color-primary-foreground: #ffffff;
                --color-secondary-foreground: #ffffff;
                --background-primary: #ffffff;
                --background-secondary: #f9fafb;
                --background-accent: #ffffff;
                --background-muted: #f3f4f6;
                --background-accent: #ffffff;
              }
            `}
          </style>
        </ThemeProvider>
      </body>
    </html>
  );
}
